"""users

Revision ID: 286720cf12e2
Revises: 
Create Date: 2024-04-18 20:22:25.223768

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '286720cf12e2'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('director',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=150), nullable=False),
    sa.Column('lastname', sa.String(length=100), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('director', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_director_lastname'), ['lastname'], unique=False)
        batch_op.create_index(batch_op.f('ix_director_name'), ['name'], unique=False)

    op.create_table('movie',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('production_year', sa.Integer(), nullable=True),
    sa.Column('is_borrowed', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('movie', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_movie_name'), ['name'], unique=False)

    op.create_table('borrowing',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('movie_id', sa.Integer(), nullable=False),
    sa.Column('borrower_name', sa.String(length=100), nullable=False),
    sa.Column('borrowed_date', sa.DateTime(), nullable=False),
    sa.Column('return_date', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['movie_id'], ['movie.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('movie_directors',
    sa.Column('movie_id', sa.Integer(), nullable=False),
    sa.Column('director_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['director_id'], ['director.id'], ),
    sa.ForeignKeyConstraint(['movie_id'], ['movie.id'], ),
    sa.PrimaryKeyConstraint('movie_id', 'director_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('movie_directors')
    op.drop_table('borrowing')
    with op.batch_alter_table('movie', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_movie_name'))

    op.drop_table('movie')
    with op.batch_alter_table('director', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_director_name'))
        batch_op.drop_index(batch_op.f('ix_director_lastname'))

    op.drop_table('director')
    # ### end Alembic commands ###
